#!/bin/bash

GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

log() {
echo -e "$1"
}

log "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"
log "${GREEN}Compiling TYPESCRIPT ${NC}"

npm run tsc --noEmit || {
log "${RED}TYPESCRIPT Compile failed ${NC}"
exit 1
}

log "${GREEN}Compile success ${NC}"
log "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"

if [ "$OSTYPE" = "msys" ]; then
exec >/dev/console 2>&1
fi

log "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"
log "${GREEN}Linting files ${NC}"

npm run lint || {
log "${RED}Linting failed ${NC}"
exit 1
}

log "${GREEN}Linting success ${NC}"
log "${GREEN}- - - - - - - - - - - - - - - - - - - - - - - - - - - -${NC}"

log "${GREEN}Running lint-staged...${NC}"
